language: php

php:
  - 7.2
  - 7.3

install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
